import { ArrowRight, BookOpen } from "lucide-react";
import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { publicApi } from "../lib/api";

export default function PostsRecentes() {
  const [posts, setPosts] = useState([]);
  useEffect(() => { publicApi.posts().then((items) => setPosts(items.slice(0, 6))).catch(() => setPosts([])); }, []);
  return <section className="py-12 md:py-20"><div className="mx-auto max-w-7xl px-4 md:px-8"><div className="rounded-[2.75rem] border-4 border-violet-200 bg-violet-50/80 p-6 shadow-xl md:p-10"><header className="flex items-end justify-between gap-5 border-b-2 border-violet-200 pb-7"><div><span className="inline-flex items-center gap-2 rounded-full bg-violet-600 px-4 py-2 text-xs font-black uppercase tracking-[.16em] text-white"><BookOpen size={15} /> Blog da escola</span><h2 className="mt-4 font-RobotoSlab text-3xl font-black md:text-5xl">Posts recentes</h2><p className="mt-2 font-comicNeue text-lg text-slate-600">Projetos, experiências e histórias das nossas turmas.</p></div><Link to="/posts" className="font-black text-violet-700 hover:underline">Ver todos <ArrowRight className="inline" size={16} /></Link></header>{posts.length ? <div className="mt-8 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{posts.map((post) => <Link key={post.id} to={`/posts/${post.id}`} className="overflow-hidden rounded-3xl bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-lg">{post.images?.[0] && <img src={post.images[0].image_url} alt="" className="h-44 w-full object-cover" />}<div className="p-5"><span className="text-xs font-black text-violet-700">{post.category}</span><h3 className="mt-2 font-RobotoSlab text-2xl font-black">{post.title}</h3><p className="mt-3 line-clamp-3 font-comicNeue text-slate-600">{post.summary}</p></div></Link>)}</div> : <p className="mt-8 rounded-3xl border-2 border-dashed border-violet-300 bg-white/70 p-10 text-center font-comicNeue text-slate-600">Os primeiros projetos publicados aparecerão aqui.</p>}</div></div></section>;
}
